variables:
  PHP74_VERSION: $PHP74
  PHP80_VERSION: $PHP80
  DOCKER_CONTEXT: ""
  BUILD_TAG: ""
  BUILD_DESTINATION: "--destination $CI_REGISTRY_IMAGE"
  KANIKO_CACHE_ARGS: "--cache=true --cache-copy-layers=true --cache-ttl=24h"
  IMAGE_LABELS: >
    --label org.opencontainers.image.vendor=ARA
    --label org.opencontainers.image.authors=rene.bakx
    --label org.opencontainers.image.source=$CI_PROJECT_URL
    --label vcs-url=$CI_PROJECT_URL
    --label build-date=$CI_JOB_STARTED_AT


stages:          
  - build

.build_docker_push:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]    
  script:
    - BUILD_DESTINATION = "$BUILD_DESTINATION:$BUILD_TAG"
    - DOCKER_CONTEXT = "$CI_PROJECT_DIR/$DOCKER_CONTEXT"
    - echo "Building $BUILD_DESTINATION at $DOCKER_CONTEXT"
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $DOCKER_CONTEXT $KANIKO_CACHE_ARGS $BUILD_DESTINATION $IMAGE_LABELS

build docker 1:2 :
  extends: .build_docker_push
  stage: build
  variables:
    DOCKER_CONTEXT: "php74"
    BUILD_TAG: $PHP74_VERSION
    IMAGE_LABELS: $IMAGE_LABELS "--label org.opencontainers.image.title="NGINX - PHP-FPM $PHP74_VERSION"

build docker 2:2 :
  extends: .build_docker_push
  stage: build
  variables:
    DOCKER_CONTEXT: "php80"
    BUILD_TAG: $PHP80_VERSION
    IMAGE_LABELS: $IMAGE_LABELS "--label org.opencontainers.image.title="NGINX - PHP-FPM $PHP80_VERSION"