variables:
  PHP74_VERSION: $PHP74
  PHP80_VERSION: $PHP80
  KANIKO_CACHE_ARGS: "--cache=true --cache-copy-layers=true --cache-ttl=24h"
  IMAGE_LABELS: >
    --label org.opencontainers.image.vendor=ARA
    --label org.opencontainers.image.authors=rene.bakx
    --label org.opencontainers.image.source=$CI_PROJECT_URL
    --label vcs-url=$CI_PROJECT_URL
    --label build-date=$CI_JOB_STARTED_AT
stages:          
  - build

.build_docker_push:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]    
  script:
     - BUILD_CONTEXT="--context $CI_PROJECT_DIR/$DOCKER_CONTEXT"
     - PHP_VERSION=$(echo "${DOCKER_CONTEXT}" | sed s/php//g)
     - BUILD_DESTINATION="--destination $CI_REGISTRY_IMAGE:$BUILD_TAG --destination CI_REGISTRY_IMAGE:$PHP_VERSION-latest"
     - echo "/kaniko/executor $BUILD_CONTEXT $KANIKO_CACHE_ARGS $BUILD_DESTINATION $IMAGE_LABELS"
     - mkdir -p /kaniko/.docker
     - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
     - /kaniko/executor $BUILD_CONTEXT $KANIKO_CACHE_ARGS $BUILD_DESTINATION $IMAGE_LABELS
  rules:
      - if: '$CI_PIPELINE_SOURCE == "web"'
        when: always
      - when: never

build docker 1:2 :
  extends: .build_docker_push
  stage: build
  variables:
    DOCKER_CONTEXT: "php74"
    BUILD_TAG: $PHP74_VERSION
    IMAGE_TITLE_LABEL: '--label org.opencontainers.image.title="NGINX - PHP-FPM $PHP74_VERSION"'

build docker 2:2 :
  extends: .build_docker_push
  stage: build
  variables:
    DOCKER_CONTEXT: "php80"
    BUILD_TAG: $PHP80_VERSION
    
